---
title: "Assignment 7 - ML reading material"
author: "YOUR NAME HERE"  
format:
  html:
    code-fold: true 
    embed-resources: true
    toc: true
    number-sections: false
    theme: cerulean
---

# Goal of this assignment  
The goal of this assignment is for you to read a blog post and answer some questions related to it.  

In specific, you will be asked to read one resource:  

1) Introduction to ML blog post:  
  - Read this blog post for an introduction to machine learning: [link](https://vas3k.com/blog/machine_learning/)  
  - If you have time, read in its entirety.  
  - If you are short on time, you **can skip** Parts 2 (reinforcement learning) and 4 (neural networks and deep learning).  
  
# Instructions  
After reading the blog post, answer the following questions.  
**NOTE**: you MUST paraphrase your answer.    
**Copy and Paste = Plagiarism = 0% grade**  

# Questions  
## 1. In your own words, describe what is machine learning.   

## 2. What are the main types of ML? List and describe them in 1-2 sentences each.   

## 3. Define supervised and unsupervised ML.  

## 4. List two algorithms/analysis considered supervised, and provide one application example.  

## 5. List two algorithms/analysis considered unsupervised, and provide one application example.  

## 6. In ensemble learning, what is the difference between bagging and boosting?  


# Submitting your work  
Once you have developed all the answers, make sure to Render this quarto file.  

**Notes on rendering**:  

- Make sure to render your work and inspect how the final html look like.  
- If it does not look professional for whatever reason, then fix the issue, re-render it, recheck.  
- Only send me your work once your html file looks professional.  
  - **DO NOT** delete the file's heading levels (# and ##). They set up the proper heading 1 and 2 levels, and I use them to guide my grading.  
  - If a given chunk is also outputting warnings or messages, inhibit this behavior by changing the chunk options `message` and `warning` to `FALSE` (I'll demo this in a moment).  
  
  - If, after rendered, 2 lines of text are connected and you wish to "break line" between them, add 2 extra spaces after the first one (I'lld demo this in a moment).  

After rendering, an .html file will be created on your `code` folder.  

Rename this file to `Assignment-07-mlread-LASTNAME.html`.    

For ex., mine would be `Assignment-07-mlread-Bastos.html`.

Submit your work by uploading the **html** file to **eLC Assignment #7 - ML read** by Monday March 16 11:59 pm.  
  




